on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: New Excavator via Hok
jobs:
  excavate:

    name: Excavate
    runs-on: windows-latest
    environment: Excavator
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Bucket
        uses: actions/checkout@v7
        with:
          path: my_bucket
      - name: Download hok (latest release)
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "maboloshi/hok"
          latest: true
          fileName: "hok.exe"
          out-file-path: "${{ runner.temp }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Excavate
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          $hok = "$env:RUNNER_TEMP\hok.exe"
          cd my_bucket
          & $hok ci-auto-pr --push -d bucket -o "${{ github.ref_name }}"
